-- Run once in the Supabase SQL Editor.
-- The app uses the server-side SUPABASE_SECRET_KEY, so public client access is not required.
create table if not exists public.runs (
    id bigint generated by default as identity primary key,
    mode text not null,
    status text not null,
    current_step text,
    run_dir text,
    config jsonb not null default '{}'::jsonb,
    step_attempts jsonb not null default '{}'::jsonb,
    budget_tokens bigint not null default 0,
    usage_tokens bigint not null default 0,
    stop_reason text,
    error text,
    report_json text,
    report_html text,
    report_json_en text,
    report_html_en text,
    events jsonb not null default '[]'::jsonb,
    artifact_key text,
    created_at timestamptz not null,
    started_at timestamptz,
    finished_at timestamptz,
    updated_at timestamptz not null
);

create index if not exists idx_runs_status on public.runs(status);
create index if not exists idx_runs_created_at on public.runs(created_at desc);
create index if not exists idx_runs_finished_at on public.runs(finished_at desc);

-- The service-role key bypasses RLS. Keep the reports bucket private.
-- No storage policy is needed for this server-side-only integration.
